[package]
name = "midi_ctrl"
version = "0.1.0"
authors = ["Matt Bilker <me@mbilker.us>"]

[dependencies]
enigo = { git = "https://github.com/mbilker/enigo.git" }
hex-slice = "0.1.2"
jack = "*"
lazy_static = "1.0.0"
rimd = { git = "https://github.com/RustAudio/rimd.git" }
